web:
  restart: always
  build: ./web/
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  env_file: env
  volumes:
    - ./web:/data/web
    - /data/web/coinsim/frontend/src/node_modules
    - /data/web/coinsim/frontend/src/fullproject
    - /data/web/coinsim/frontend/dist
    
  command: /data/web/docker-entrypoint.sh



nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./pg-data:/var/lib/postgresql/data
  env_file:
    - env
  expose:
    - "5432"
 
redis:
  restart: always
  image: redis:latest
  expose:
    - "6379"


