# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_currency',
            field=models.CharField(choices=[('Food Court', 'Food Court'), ('KFC', 'KFC')], max_length=32),
        ),
    ]
