# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171208_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_currency',
            field=models.CharField(max_length=32),
        ),
    ]
