# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171208_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sym', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='to_currency',
            new_name='dest_currency',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='new_balance_to',
            new_name='new_balance_dest',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='new_balance_from',
            new_name='new_balance_source',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='from_currency',
            new_name='source_currency',
        ),
    ]
