# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='new_balance_dest',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance_source',
            field=models.FloatField(null=True),
        ),
    ]
