# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-17 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171217_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='color',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
