# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-17 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_balance_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='color',
        ),
        migrations.AddField(
            model_name='currency',
            name='color',
            field=models.CharField(default='#C6EB6A', max_length=32),
        ),
    ]
