# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-17 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171217_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dest_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
