# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180118_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=1048576)),
                ('lang', models.CharField(default='en_US', max_length=32)),
            ],
        ),
    ]
