# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180123_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
