# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cryptodescription'),
        ('api', '0014_auto_20180123_0738'),
    ]

    operations = [
    ]
