# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20180123_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='balance',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cryptodescription',
            name='text',
            field=models.TextField(),
        ),
    ]
