# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-29 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180123_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.SmallIntegerField()),
                ('roi', models.FloatField(default=0)),
                ('totalBTC', models.FloatField(default=0)),
                ('totalUSD', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='api.Profile')),
            ],
            options={
                'ordering': ['pos'],
            },
        ),
    ]
